services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    build:
      context: ./src/caddy
      dockerfile: ./Dockerfile
    env_file:
      - src/caddy/creds.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    networks:
      - ingress

networks:
  ingress:
    name: ingress
    driver: bridge
