name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push'
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: deployment check
        uses: github/branch-deploy@v10

        id: deployment-check
        with:
          merge_deploy_mode: "true"
          environment: production

      - name: fetch repo name
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        id: repo_name
        run: echo "repo_name=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_OUTPUT

      - name: checkout
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        uses: actions/checkout@v4

      - name: ssh remote deploy
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        uses: appleboy/ssh-action@8faa84277b88b6cd1455986f459aa66cf72bc8a3 # pin@v1.2.1
        with:
          host: ${{ vars.SSH_HOST }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: ~/${{ steps.repo_name.outputs.repo_name }}/script/deploy -r "main" -d "/home/${{ secrets.SSH_USERNAME }}/${{ steps.repo_name.outputs.repo_name }}"
